### ISSUE TITLE
Get the addin listed on cake website

### ISSUE THREAD

**Issue by AdmiringWorm** [WormieCorp/Cake.Transifex#2]
Example PR: https://github.com/cake-build/website/pull/290

thanks to @gep13 that gave me the example PR link

Maybe adding namespace documentation as mentioned here: http://cakebuild.net/docs/contributing/documentation#namespaces

Not sure if it's needed when namespace is imported.

**Comment by gep13** [comment]
@AdmiringWorm looking at your code, everything is under the `Cake.Transifex` namespace, so you won't need the Namespaces.cs file.

**Comment by AdmiringWorm** [comment]
@gep13 yeah, thanks. I wasn't entirely sure if it was needed or not.
